# Generated by Django 4.2.2 on 2023-06-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natureapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='titulo',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
